server:
  port: 90
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.221.128:3306/volume_up_health?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  jackson:
    date-format:
    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:mappers/*.xml
logging:
  level:
    com.voumel.up.web.mapper: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
